export const SET_USER_DATA = 'SET_USER_DATA'
export const TOGGLE_API_CALL_ACTIVE = 'TOGGLE_API_CALL_ACTIVE'
export const SET_ACTIVE_USERNAME = 'SET_ACTIVE_USERNAME'
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS'
